### ISSUE TITLE
AS dependency: add the number of hops for dependent network

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#10]
We want to know how far are dependencies, the list of ASN could be sorted by the number of hops

**Comment by kkartik07** [comment]
@romain-fontugne Is this issue related to this?
![image](https://user-images.githubusercontent.com/87076033/225211671-5972d226-116b-4730-9dab-a7724057073f.png)

I can take this, please assign me this issue.

**Comment by ConnectBhawna** [comment]
@romain-fontugne sir, i would like to work on this.
Can you please give us some brief about the issue, it would be really helpful

**Comment by romain-fontugne** [comment]
@kkartik07 , no it is not related.

This issue actually show probably fixed in the backend. This is something we can compute in our backend and show in the api

**Comment by pankaj87072** [comment]
hey @romain-fontugne can i work on this issue 
as per my understanding i think we can implement a backend code in as-hegemony to calculate the no of hops from source to destination and then show it in coloumn is that right aproach?

**Comment by romain-fontugne** [comment]
yes, we could add that in the as-hegemony code, in this case we should open an issue there. But actually now that we have integrated the IHR website with IYP we could just modify the 'downstream stream' widget in network/routing to show this information from IYP

**Comment by pankaj87072** [comment]
@romain-fontugne 
My points on this issue:-
The main aim of this issue is to find the number of hops between the origin AS and all its dependencies, as shown in the AS dependency section. The result should be sorted in ascending order based on the number of hops. It's important to note that we're not looking for the number of hops within the network of the origin AS, but rather between the origin AS and all its dependencies as i have wasted a lot of time by misunderstanding the issue.  
#########################################################
Approach to solve this (according to my understanding):-
   a:-Modify the bgpatom_loader code responsible for processing AS paths and prefixes. We need to incorporate logic to calculate the number of hops between the origin AS and each of its dependencies. This can be achieved by analyzing the length of the AS path. 
   b:-, we can enhance the bgpatom_peer code, which is responsible for processing and establishing relationships (peers) between ASes. Since bgpatom_peer already utilizes AS path data, we can extend it to calculate the length of the AS path from the origin AS to each of its dependencies.

**Comment by romain-fontugne** [comment]
yes, that issue should be first addressed in the as-hegemony repository. I'm closing this issue for now as we cannot add anything on the website until that feature is added there.
