### ISSUE TITLE
Unable to add destination under Network delay

### ISSUE THREAD

**Issue by swapneelp** [InternetHealthReport/ihr-website#22]
Thank you for building this. There is a lot of interesting data and patterns. 

I am trying to add a destination network AS24186 under Network delay and have been unable to add it. I am guessing it does a traceroute return path using atlas like,

`ripe-atlas measure traceroute --from-asn 16509 --target "IPADDRESS"`

where IP address is from one the of prefixes of AS24186, please correct me if I am wrong. 

When I enter the ASN(AS24186) and click on add, nothing happens. FYI, I have a probe running on [AS24186](https://atlas.ripe.net/probes/1000272/).

**Comment by romain-fontugne** [comment]
Hi,

I think we don't have network delay results to AS24186 because it doesn't appear in the traceroutes we analyze, we are not analyzing all Atlas traceroutes.
Because there is too much data in Atlas for us to analyze, we compute network delays only from 'long lasting' measurements. That includes built-in measurements and anchoring measurements. So the best way to have AS24186 appear in our results is to host a RIPE anchor on AS24186.

I am curious about you probe, is it not doing built-in measurements?

**Comment by swapneelp** [comment]
@romain-fontugne Thank you for the detailed response. It's now clear to me how this works. 

It's really weird that the probe isn't doing built-in measurements since 19-3-2020. This is a software probe and the only one showing this issue. I'll check. Thank you for pointing it out. 👍
