### ISSUE TITLE
Development server has not been setup properly in windows OS

### ISSUE THREAD

**Issue by Arunjagan12** [InternetHealthReport/ihr-website#253]
While setting up the development in windows, I followed the steps in the development guide and gave npm commands. But the code was executed due to some errors in the scripts in package.json file.

**Comment by Arunjagan12** [comment]
Can u assign me to solve this as I have made some changes in package.json and it worked perfectly.

**Comment by romain-fontugne** [comment]
I have no idea on how to develop on windows :D
Feel free to make a PR for this but please make sure it doesn't brake things on linux

**Comment by Arunjagan12** [comment]
Yeah sure it's a simple command so it doesn't affect other os users

**Comment by Avi-88** [comment]
Hi @Arunjagan12 , this issue exists not only for windows but others OS also. It is because of the SSL hole fixed when node v17 was released , the fix you suggested will work but its a workaround nonetheless. We need to actually update all packages with latest security updates which may introduce a lot of breaking changes. Another workaround is to use a downgraded node version (v16) instead of changing the package.json , we can update the setup guide to do instruct the same , would like to know your thoughts on this, thanks

**Comment by romain-fontugne** [comment]
I have merged the PR as a workaround. But @Avi-88 is right we should document that and eventually fix the problem

**Comment by ConnectBhawna** [comment]
May i work in this issue @romain-fontugne sir.
Can you please give me some insights like exactly on which i need to work. Would be happy to work on this :)

**Comment by romain-fontugne** [comment]
It looks like our code is not working with node v17 and higher. I'm not entirely sure about the problem, but as @Avi-88 mentioned it seems to be related to an SSL problem

**Comment by ConnectBhawna** [comment]
Okk sir

**Comment by Arunjagan12** [comment]
Yes,  I have made some changes for now but  
but it's not a permanent solution. The changes in the documentation will help the new contributors for now.

**Comment by dpgiakatos** [comment]
closed by [#669](https://github.com/InternetHealthReport/ihr-website/pull/669)
