### ISSUE TITLE
Integrate up/down probes ObservableHQ viz into IHR

### ISSUE THREAD

**Issue by emileaben** [InternetHealthReport/ihr-website#270]
**Describe the solution you'd like**
With a colleague I created a simple/alternative view of RIPE Atlas probes going up and down, per country/ASN/geographic region. It is here: https://observablehq.com/@ripencc/internet-outages-as-seen-by-ripe-atlas . I think it is a concise view of an Internet event happening, so I would love to see it integrated in various parts of IHR.
For instance: 
* for the per ASN page , show the Atlas probes over time for that ASN for the same time period as the hegemony scores for that ASN
* for the per country page , show the Atlas probes in the country for the last few days

(and/or any other integrations as is seen fit)

**Comment by romain-fontugne** [comment]
Yes, we absolutely need to integrate that to IHR :)

We still have no experience importing stuff from observable. So maybe an easy first step would be to have the code show up in a new page, then we could think of how to integrate it around the other visualization.

**Comment by Aniket762** [comment]
@romain-fontugne once, we have our exploratory dashboard done. May be we can get it done in the first go and integrate over there itself. 

If you want, I would work in with some contributors and get it done as soon as possible.

**Comment by aabhas-sao** [comment]
I would like to work on this is issue. I would really like to work on this exploratory dashboard.


I'm Aabhas Sao, a final year student from NIT Rourkela. I have been interested in software development since early childhood. I started learning on my own in first year of my college. Since then I have interned at 2 startups. 

At Avalon Scenes I used to manage all the deployments of client apps on Play Store and App Store. Along with one of co-founders I also worked on app-inside-app concept which will potentially bring $120000 revenue annually and create a new stream of revenue. I also worked with Vue at Advect Systems to create a client GUI for a 3D printing system. Using the client UI users can make changes like transform, crop etc. before printing the model. I also worked on dockerizing the backend server for portability.

I love contributing to open-source and last summer I contributed to Jenkins X to improve arm cpu architecture support for M1 mac and in the process I learned Golang and managed to merge 10+ PRs.
 
Being from Industrial Design department I have basic understand of design and can help with prototyping and improving the UI/UX of exploratory dashboard.

I like to build things and so with my team have participated and won over 10 international hackathons. Conducted by organisations like Xiaomi, Uber, Juspay, MLH etc.

@romain-fontugne and @Aniket762 it will be really great if you could mentor me and we can work on this issue.

**Comment by Arunjagan12** [comment]
@Aniket762 can we work on this issue??.I went through the link and I know the purpose of ripe atlas but I don't know what to do here exactly??the task is to integrate the ripe atlas probes on IHR ryt??I am not fully clear about it.Can u elaborate it??

**Comment by Aniket762** [comment]
> I would like to work on this is issue. I would really like to work on this exploratory dashboard.
> 
> I'm Aabhas Sao, a final year student from NIT Rourkela. I have been interested in software development since early childhood. I started learning on my own in first year of my college. Since then I have interned at 2 startups.
> 
> At Avalon Scenes I used to manage all the deployments of client apps on Play Store and App Store. Along with one of co-founders I also worked on app-inside-app concept which will potentially bring $120000 revenue annually and create a new stream of revenue. I also worked with Vue at Advect Systems to create a client GUI for a 3D printing system. Using the client UI users can make changes like transform, crop etc. before printing the model. I also worked on dockerizing the backend server for portability.
> 
> I love contributing to open-source and last summer I contributed to Jenkins X to improve arm cpu architecture support for M1 mac and in the process I learned Golang and managed to merge 10+ PRs.
> 
> Being from Industrial Design department I have basic understand of design and can help with prototyping and improving the UI/UX of exploratory dashboard.
> 
> I like to build things and so with my team have participated and won over 10 international hackathons. Conducted by organisations like Xiaomi, Uber, Juspay, MLH etc.
> 
> @romain-fontugne and @Aniket762 it will be really great if you could mentor me and we can work on this issue.

Hey @aabhas-sao your profile and background looks good to me. Let's work together and hop on a call where we can discuss poas

**Comment by romain-fontugne** [comment]
first you can try to call the observable code sent by emileaben from ihr website. Then we can discuss how to make it look better/integrate better with the website UI.

**Comment by niladrix719** [comment]
i can work on this if it is free

**Comment by aabhas-sao** [comment]
> first you can try to call the observable code sent by emileaben from ihr website. Then we can discuss how to make it look better/integrate better with the website UI.

Got it. Will try integrating the observable chart.

**Comment by aabhas-sao** [comment]
I had started trying to integrate a notebook in to the existing site.

Observable notebooks can be embedded as `npm modules`, they need to be published publically for that and I have been trying this method. By creating a seperated Vue compoenent. For embedding doc see [this](https://observablehq.com/@observablehq/advanced-embeds). 

Initially I faced 3 errors due to `observablehq` having features like `nullish coalescing` and `import.meta` which was not getting transpile correctly, after configuring babel properly this has been resolved.

Now there are errors due to dynamic imports with static urls being used in module exported from  notebook.

<img width="882" alt="Screenshot 2023-04-10 at 9 22 54 AM" src="https://user-images.githubusercontent.com/58210877/230822330-8976fefd-f293-46a3-b936-7d1885757570.png">

I have pushed progress till now to my local branch https://github.com/aabhas-sao/ihr-website/tree/feat/270/observable-integration.

Below screenshots contain import code due to which error is generated from notebooks npm module. 
This is related to webpack and I'm trying to resolve this. 

<img width="869" alt="Screenshot 2023-04-10 at 9 08 39 AM" src="https://user-images.githubusercontent.com/58210877/230820858-27fc3a14-cf49-43ff-9245-6374defa3df5.png">

<img width="851" alt="Screenshot 2023-04-10 at 9 13 11 AM" src="https://user-images.githubusercontent.com/58210877/230821358-94eaa922-c078-4d8e-92f0-2a1435617b7c.png">

**Comment by aabhas-sao** [comment]
hey @emileaben  and @romain-fontugne,
I was able to integrate the observable notebook in a separate route.
But I had to patch some of the code in the notebook module to make it work. Currently integration process is painful and needs some manual effort.

Currently we are using Webpack 4x, upgrade to Webpack 5x might solve some of these issues. Will try that.
Let me know how we should proceed further.

Also one thing I discovered that Vue 2 LTS is reaching end of lifecycle this December. [article link](https://v2.vuejs.org/lts/)


https://user-images.githubusercontent.com/58210877/231452683-14828d54-9e13-4d34-ab1c-42eebdb0ad1f.mov

**Comment by roopeshsn** [comment]
Why integrate notebooks from Observablehq directly to the website? Instead, we can use the same code by creating components right? It will reduce a lot of headache.

**Comment by aabhas-sao** [comment]
> Why integrate notebooks from Observablehq directly to the website? Instead, we can use the same code by creating components right? It will reduce a lot of headache.

hey @roopesh,

A few things I think is positive when using observable notebooks embedding,
1. Development time for native components will be comparatively a lot more. Using same API used in notebook, rewriting whole logic for native components.
2. The ability to add any observable notebook will mean we can directly integrate any notebook prepared by internet researchers (of course with some cleaning).
3. Some people might prefer to work with observable for visualisations and may not want to explicitly like to contribute to IHR but like to see that chart being imported if it's very useful internet usage metric.

@romain-fontugne if you would like to add any more benefits of integrating observablehq or correct me if I have understood something wrong, would like to know.

Although I'm not sure about stability and performance of these integrations 😂. But I believe integrating can be made simpler by either exploring features and behaviour of module bundler used (Webpack) or writing a custom script to patch files as per current requirement.

**Comment by aabhas-sao** [comment]
Hey @romain-fontugne below is a guide for embedding a notebook. I have tried this on fresh clone to be sure it works. We don't require to make changes to the observable notebook but the exported code provided by observable.
Let me know steps which are unclear. 

Also some more drawbacks of this approach is that we have to commit assets used by notebook and the patched notebook module to source code.

If we can eliminate need to patch manually we can use observable notebooks published online, which will enhance the whole workflow. For the next two weeks I'll be busy with final exams so haven't been able to work on creating a better workflow but if anyone wants to take this work further and try enhancing it, i'll be glad and help out as much I can.



## Steps for initial Setup
1. Install @vue/babel-preset-app and @observablehq/runtime@5
  ```
    npm i @vue/babel-preset-app
    npm i @observablehq/runtime@5
  ```
2. In `babel.config.js` add preset @babel/preset-env
  ```
    presets: [['@vue/app', { useBuiltIns: 'entry' }], ['@babel/preset-env']],
  ```
## Steps for Embedding Notebook
3. Add `@observablehq` and `d3-chart` (let's say this is notebook package name) to the transpileDependencies in `vue.config.js`
  ```
  transpileDependencies: [
    /[\\/]node_modules[\\/]quasar[\\/]/,
    '@observablehq',
    'd3-chart',
  ],
  ```
(Note you can ommit observablehq if already in package.json and transpileDependencies list)

4. Download notebook by going to  `Export > Download Code`
<img width="1440" alt="Screenshot 2023-04-19 at 5 52 00 PM" src="https://user-images.githubusercontent.com/58210877/233073369-b4739385-af0e-4788-8088-bf6655f36064.png">

5. Patch all `JavaScript files`
  - Add webpackIgnore magic comment to dynamic imports below like. This makes webpack to ignore these imports to be bundled and are handled later by the client browser. 
  ```
  import(/* webpackIgnore: true */ `https://api.observablehq.com/@tomlarkworthy/testing.js?v=3`)
  ```

  - Change fileAttachments containing `import.meta.url` to static imports. This is a modern feature and `import.meta` helps module bundler know that these static assets need to be bundled as well. I guess webpack 4x doesn't support this but 5x does.
  - From
  ```
  ["image@1.png", {url: new URL("./files/image.png", import.meta.url), mimeType: "image/png", toString}]
  ```
  - To
  ```
  ["image@1.png", "/files/image.png"]
  ```

6. Transfer all assets from `d3-chart/files/` to `public/files/` folder of `ihr-website` root directory.

7. After patching the `d3-chart` module package it again by
running 
```
  npm pack
```
in the d3-chart directory in terminal.

8. Npm will generate a file like `d3-chart-60.0.0.tgz`, now move this package generated by npm to `lib/notebooks` in ihr-website root directory. 

9. To install the notebook package `d3-chart` either run 
```
  npm i ./lib/d3-chart-60.0.0.tgz
```
or add
```
  "d3-chart" : "file:lib/notebooks/d3-chart-60.0.0.tgz"
```
to dependencies in package.json and run 
```
  npm i
```

## Using the Notebook
1. Create a custom component to use the notebook.

  - Let's call the component name ProbesReport
  - Create a new file in `components/notebooks` named ProbesReport.vue
  
   ```jsx
    <template>
    <div>
      <h1>Observable Integration</h1>
      <div ref="ref"></div>
    </div>
    </template>

    <script>
    import { Runtime, Inspector } from '@observablehq/runtime'
    import notebook from 'd3-chart'

    export default {
    data() {
      return {
        notebookModule: null,
      }
    },
      mounted() {
      const runtime = new Runtime()
      const inspect = Inspector.into(this.$refs.ref)
      this.notebookModule = runtime.module(notebook, inspect)
      },
    }
    </script>
  ```

  Above is an example code for importing all cells of a notebook.

 - Now this notebook can be used as a vue component anywhere in the project.

**Comment by romain-fontugne** [comment]
Thanks! sorry for the late reply. I still have to try that. At a glance, it looks good to me
