### ISSUE TITLE
Address Linting Warnings

### ISSUE THREAD

**Issue by aabhas-sao** [InternetHealthReport/ihr-website#277]
**Describe the bug**
while running the server `es-lint` shows a lot of warnings. Some of them can simply be fixed by excluding `node_modules` from being linted.

**To Reproduce**

1. Go to `ihr-website` directory
2. run `npm install`
3. run `npm run serve`
4. after compilation linting warnings show up.

**Expected behavior**
Address some of the warnings to improve code quality. Remove unused imports, etc.

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-26 at 1 54 50 PM" src="https://user-images.githubusercontent.com/58210877/221400015-0088b69b-9d48-4780-9cf1-77e8b2c9e4e9.png">

**Comment by ConnectBhawna** [comment]
Great Point out @aabhas-sao Can work on this.
Let me know if you are interested in working on this? 
Otherwise i will make a PR for this, Thanks

**Comment by aabhas-sao** [comment]
Hey @ConnectBhawna thnx. Let me try working on this. I'll let you know if I get stuck. Hey @Aniket762 can you assign me this issue to avoid confusion.

**Comment by Aniket762** [comment]
Hey @aabhas-sao go for it. To fix the linting errors, I guess you need to change the filenames. Before you push your final commits and send the PR. Do send here the file names and other major changes you are looking forward to. 

Since, there will be intensive amount of code changes. I hope, you test well and send a video the site working. 

@ConnectBhawna let's empower aabhas to start his opensource journey with IHR 💪. There are issues, I will be listing on which you can work on. Hope you don't mind.

**Comment by ConnectBhawna** [comment]
Sure @Aniket762 sir no issues. I am working on another issue till than
@aabhas-sao do let me know if you face any issue. Would love to help you out :)
Happy Hacking
