### ISSUE TITLE
Error while installing project locally

### ISSUE THREAD

**Issue by kkartik07** [InternetHealthReport/ihr-website#331]
While I was setting up IHR-website on my local machine, the 'npm run serve' gave error "node: --openssl-legacy-provider is not allowed in NODE_OPTIONS". On searching I found that, --openssl-legacy-provider flag is not allowed to be set in the NODE_OPTIONS environment variable. This may be due to security restrictions or a newer version of Node.js that no longer supports this flag.

So on changing "serve": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve" in package.json to "serve": "set NODE_OPTIONS=--openssl-legacy-provider || vue-cli-service serve", it gave no error.

**Comment by anugcodes** [comment]
I had faced a issue while setting up the development environment in Linux environment
![serve error](https://user-images.githubusercontent.com/110781959/225232469-e2039401-b8ae-40b1-a0a3-8661cd54ec35.png)
this error is due to the command 
`set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve`
that can be replaced with
`export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve` for the Linux machines.

we can find a way to make the script run for both the platforms

**Comment by kkartik07** [comment]
@anugcodes I was installing it on my windows machine and it gave error with  "serve": "set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
![image](https://user-images.githubusercontent.com/87076033/225237284-7ca6f62e-6f5f-4b93-8b13-4be77a7939be.png)
But on replacing the same with  "serve": "set NODE_OPTIONS=--openssl-legacy-provider || vue-cli-service serve" OR "serve": "vue-cli-service serve"
, it worked.
On searching I found out that,  --openssl-legacy-provider flag is not allowed to be set in the NODE_OPTIONS environment variable. This may be due to security restrictions or a newer version of Node.js that no longer supports this flag.

**Comment by thisiskaransgit** [comment]
@kkartik07 @anugcodes , we have been having issues with node v17 or higher, it's a compatibility issue, 

Even though it is a workaround kindly downgrade the node version to node v16, this should fix the issue, irrespective of the OS used. 
My advice would to be get familiar with and use [nvm(node version manager)](https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/), I am using it and get my works done.
We are looking for the root cause for this but for now this will get you started.

Do this : 
1. nvm use lts/gallium 
2. npm install 
3. npm run
