### ISSUE TITLE
Some UI fixes

### ISSUE THREAD

**Issue by Yh010** [InternetHealthReport/ihr-website#362]
**Describe the bug**
A clear and concise description of what the bug is :

1)The alignment of the graph and the icons should be changed

![Screenshot (284)](https://user-images.githubusercontent.com/77537293/226822507-ead3fd87-8c97-4aab-aa6a-74128254c6f7.png)

2)in the below graph, the icons row should be taken a bit higher

![Screenshot (283)](https://user-images.githubusercontent.com/77537293/226822810-4575cce6-c05c-4cf5-ae62-e9e8dbd5a347.png)

3)instead of downloading the plot as png, maybe we could download it as pdf as a pdf would be more beneficial for further file sharing and research purposes

If the issue is relevant can I work on this issue?

**Comment by thisiskaransgit** [comment]
If you are proposing to make changes within the plots, it won't be possible since the code for that isn't available on the website repo, they are being shown with API calls, the website is just managing the state and the layout. 

and with respect to downloading the report as a pdf, I had implemented it before, but since it wasn't needed, for now, it has been removed.

I hope I am right, @romain-fontugne @Aniket762

**Comment by Yh010** [comment]
@thisiskaransgit actually I was pointing out the location of the icons and the plot, as in we can just space out things to make the appearance a bit better

**Comment by Yh010** [comment]
Ohk so @thisiskaransgit the icons are also being generated by the API along with the graph right?

**Comment by kanishk88** [comment]
> Ohk so @thisiskaransgit the icons are also being generated by the API along with the graph right?

yes, the different tools are being generated along with the graph with the help of a library rather than an api.
