### ISSUE TITLE
Global Report page's internal links not working properly.

### ISSUE THREAD

**Issue by anugcodes** [InternetHealthReport/ihr-website#382]
**Describe the bug**
Internal page navigation links not working properly on the Global Report page.
- the As dependency alarms button do not navigate to the corresponding section instead it loads the homepage.
- the network delay alarms button do not do anything.
- the link delay alarms button and the network disconnection alarms works fine

**To Reproduce**

1. Go to 'http://localhost:8080/ihr/en-us/global_report?filter_level=1&last=3&date=2023-03-29'
2. Click on all the buttons on the internal navigation section.

**Expected behavior**
- the As dependency alarms button should not redirect to another page and should navigate to the As dependency section
- the network delay button should navigate to the corresponding section.

**Screenshots**
![finalIssue](https://user-images.githubusercontent.com/110781959/228551594-893c84c8-31cb-4375-abce-d6c3a5d6892a.jpg)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser [Firefox]
- Version [110.0. 1]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Soohti** [comment]
The network delay button works well on my side. I just quickly fixed the As dependency alarms button.

**Comment by thisiskaransgit** [comment]
@anugcodes, 
The problem that you're referring to isn't being produced in the build, kindly recheck it, Also a side note, never include the localhost link for the reproduction of issue, we aim to solve the problems related which are reflected in the production build and hence the link of the same should be included.

**Comment by thisiskaransgit** [comment]
It looks like you, the way you phrased the issue is wrong, but I got what you are referring to,  so thank you for this issue, the problem lies in the query params as the buttons change the routes, and thus we are unable to see the site when the link is copied.

@romain-fontugne, you can reproduce the issue 
1. Go to: https://ihr.iijlab.net/ihr/en-us/global_report
2. Click on any of the alarm button (example : Network Delay ) 
3. See the updated query 
It should have been

 https://ihr.iijlab.net/ihr/en-us/global_report?[filter]#networkDelay
 
 but, it is coming as //ihr.iijlab.net/ihr/en-us/#networkDelay

**Comment by romain-fontugne** [comment]
OK, I see, thanks!

**Comment by Soohti** [comment]
I agree with @thisiskaransgit that this PR does not solve the issue when copying the link. However, this PR is just reverting the unintentional change brought in by https://github.com/InternetHealthReport/ihr-website/commit/e4198fe46bc41b748cf489228231d33d4fd4a35d. Therefore there's no need of reverting it again. @romain-fontugne

**Comment by Soohti** [comment]
Thanks @thisiskaransgit for looking into this issue

**Comment by thisiskaransgit** [comment]
@Soohti, okay, since you stated in the PR that it fixes the issue, it created the misunderstanding, edit it to state the changes you made, and if you need to discuss anything else we can do it on slack. 

@romain-fontugne We do not need to reopen it, I'll make raise a new issue, stating the current and desired behavior, and make a PR stating all the changes.

**Comment by thisiskaransgit** [comment]
@Soohti, okay, since you stated in the PR that it fixes the issue, it created the misunderstanding, edit it to state the changes you made, and if you need to discuss anything else we can do it on slack. Let this be closed we do not need to extend the discussion here

@romain-fontugne We do not need to reopen it, I'll make raise a new issue, stating the current and desired behavior, and make a PR stating all the changes. Let this be closed we do not need to extend the discussion here
