### ISSUE TITLE
Correct message when no dependency

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#5]
There is two possibilities for a network with no AS dependency:
- the network is super distributed and really has no dependency (e.g. Google)
- the network announce no IP space

distinguish both cases using results from the global graph, and print corresponding messages

**Comment by romain-fontugne** [comment]
This issue is related to the views/charts/AsInterdependenciesChart.vue component. The graph may be empty if we measured no network dependency (e.g. https://ihr.iijlab.net/ihr/en-us/networks/AS15169?af=4&last=3&date=2019-03-15&rov_tb=routes) in this case we want to show a message "No network dependency".
But sometimes the graph is empty because we have no data for the selected network (e.g. https://ihr.iijlab.net/ihr/en-us/networks/AS6555?rov_tb=routes). AS6555 is registered but actually not connected to the global Internet. In this case we want to show a message like "Network unreachable".

To differentiate between the two cases we can do the following API calls: 
For google we have a result, that means AS15169 (Google) is active:
- https://ihr.iijlab.net/ihr/api/hegemony/?originasn=0&asn=15169&af=4&timebin__gte=2019-03-15T15%3A00%3A00.000Z&timebin__lte=2019-03-15T15%3A15%3A00.000Z&ordering=timebin

Here the result is empty, that means the network 6555 is inactive/unreachable:
- https://ihr.iijlab.net/ihr/api/hegemony/?originasn=0&asn=6555&af=4&timebin__gte=2019-03-15T15%3A00%3A00.000Z&timebin__lte=2019-03-15T15%3A15%3A00.000Z&ordering=timebin

I hope it helps?

**Comment by ConnectBhawna** [comment]
@romain-fontugne @Aniket762 sir,
Could you please assign this issue to me? I am willing to work on this.
Thanks

**Comment by romain-fontugne** [comment]
here you go!

**Comment by ConnectBhawna** [comment]
@romain-fontugne Sir. Can we do this like this?
import axios from 'axios'

axios.get('https://ihr.iijlab.net/ihr/api/hegemony/', {
  params: {
    originasn: 0,
    asn: 15169,
    af: 4,
    timebin__gte: '2019-03-15T15:00:00.000Z',
    timebin__lte: '2019-03-15T15:15:00.000Z',
    ordering: 'timebin'
  }
})
.then(response => {
  // handle response
})
.catch(error => {
  console.error(error)
})


In the example above, we are calling the first API endpoint to check if AS15169 is active. The axios.get() method takes the API endpoint URL as its first argument and an object containing the query parameters as its second argument. The .then() method is used to handle the response from the API and the .catch() method is used to handle any errors that may occur. You can modify the code to call the second API endpoint to check if AS6555 is reachable.

**Comment by Yh010** [comment]
@ConnectBhawna maybe you could modify the code to :
// set loading spinner to true
this.isLoading = true;
// clear the message
this.message = '';

axios.get('https://ihr.iijlab.net/ihr/api/hegemony/', {
  params: {
    originasn: 0,
    asn: 15169,
    af: 4,
    timebin__gte: '2019-03-15T15:00:00.000Z',
    timebin__lte: '2019-03-15T15:15:00.000Z',
    ordering: 'timebin'
  }
})
  .then(response => {
    if (response.data.length > 0) {
      // Network is announcing IP space
      this.message = 'Network is super distributed';
    } else {
      // Network is not announcing any IP space
      this.message = 'Network is not announcing any IP space';
    }
  })
  .catch(error => {
    console.error(error);
    this.message = 'An error occurred';
  })
  .finally(() => {
    // set loading spinner to false
    this.isLoading = false;
  });

code changes:

1).then(response) code block is for displaying the messages . The code snippet checks the length of the data returned by the API call .if the length of the response data is greater than 0, it means that there are dependencies and the network is reachable.And since a superdistributed network can announce IP space but still have no AS dependencies, we can say that a response data length > 0 indicates a super distributed network.On the other hand, if the length of the response data is 0, it means that there are no dependencies and the network is not announcing any IP space

2).finally code block added . By using the finally block, the code ensures that the loading spinner will always stop, regardless of whether the request was successful or not. This means that the spinner won't continue to spin indefinitely if there's an error, which can help improve the user experience. Additionally, by setting this.message to an empty string before making the API call, the message will be cleared even if the request fails. This can help prevent confusing error messages from being displayed to the user.

**Comment by romain-fontugne** [comment]
oh I think you don't need to do new API calls, the views/charts/AsInterdependenciesChart.vue  component is already calling this API. 
It is more  a matter of properly checking what is returned by the API in the component and displaying the corresponding message

**Comment by ConnectBhawna** [comment]
Okk sure sir, almost done with this issue :)
Thanks for helping me out @romain-fontugne @Yh010
