### ISSUE TITLE
Enhance Test Suite for IodaApiPlugin Module

### ISSUE THREAD

**Issue by RickDeb2004** [InternetHealthReport/ihr-website#693]
**Possible Advancements:**

- **Mocking API Calls:**
      It's a good practice to mock API calls to external services during testing to ensure that tests remain isolated and do not depend on external services. You can use Jest's mocking capabilities to achieve this.

- **Parameterized Tests:**
     Consider using parameterized tests to cover a broader range of scenarios. This can be especially helpful for functions like getIodaEntityInfo where different entity types are tested.

- **Async/Await Error Handling:**
    The code uses asynchronous functions, and it's advisable to handle errors appropriately using try-catch blocks or .catch() with Promises.

**Comment by RickDeb2004** [comment]
@romain-fontugne willing to raise a PR for this.

**Comment by RickDeb2004** [comment]
> @romain-fontugne willing to raise a PR for this.

if possible assign me

**Comment by romain-fontugne** [comment]
Please discuss this with @mohamedawnallah before submitting a PR

**Comment by RickDeb2004** [comment]
> Please discuss this with @mohamedawnallah before submitting a PR
> 

Sure

**Comment by mohamedawnallah** [comment]
### Reasons Not to Mock API Calls for `IodaApiPlugin` Module:

1. **False Positives**: Mocking can lead to misleading test results where the test always passes, but the actual data might not be valid.

2. **External Dependency (IODA Alarms)**: Trusting that data always matches the modeled schema due to mocking may not reflect the validity of the external dependency, IODA alarms.

3. **Lack of Other Test Cases**: Currently, there aren't other test cases utilizing the mocked results.

### Parametrized Tests Consideration:

For this scenario, parametrized tests might not be necessary as we typically deal with two categories: `asn` and `country`.

### Approach on `async` and `await`:

Using the `async` and `await` syntactic sugar approach appears more readable and consistent across all test cases.

**Comment by RickDeb2004** [comment]
@mohamedawnallah okay .
