### ISSUE TITLE
missing points in plots for delays are not properly handled

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/ihr-website#7]
see: http://localhost:8080/7922/asn/?af=4&date=2018-05-30&last=7

**Comment by kkartik07** [comment]
@romain-fontugne Can you please explain this briefly?
also the above link takes me to a page not found.

**Comment by juhiechandra** [comment]
@romain-fontugne Could you please brief about the issue in the description? This issue seems related to IHR-Dashboard.

**Comment by romain-fontugne** [comment]
Sometimes we have missing data in our graphs but plotly always  connect consecutive points even if there is a few missing points in between. 
Here is an example: https://ihr.iijlab.net/ihr/en-us/networks/AS3269?rov_tb=routes
![image](https://user-images.githubusercontent.com/1373917/226931749-e75e985f-4a98-4ee9-baef-2aa4b1d9c7ce.png)
There is a lot of missing points for London between 11:45 and 16:15 but because plotly connects all available datapoints it hides the missing data..

**Comment by Rithvik-padma** [comment]
@romain-fontugne I would like to work on this, can you assign this to me?

**Comment by romain-fontugne** [comment]
go ahead @Rithvik-padma

**Comment by Rithvik-padma** [comment]
@romain-fontugne The type of graph used for representing data is 'lines' because of which the data is interpolated and because of which the missing data is not visible. Possible ways to fix this problem are by either using the 'markers' type or the 'lines+markers' type
I am sharing pics for the graphs

## Markers
![image](https://user-images.githubusercontent.com/99183441/230466480-0fe6151a-172b-4b04-91ec-c9cd77734924.png)
## Lines+Markers
![image](https://user-images.githubusercontent.com/99183441/230466857-ec113ff5-6188-4521-a9e6-a7f1369e73e9.png)

I just wanted to know whether is this what you wanted to have. If this is not what was intended then can you please give some more insights on it?

Thanks!

**Comment by romain-fontugne** [comment]
thanks, I think I prefer when there a line. But I really wished that the line gets cut when there is missing data, but that's maybe not possible with plotly. Or maybe we should create different traces with the same color? (one before the cut and one after) but then I'm afraid that the legend will have duplicated entries

**Comment by romain-fontugne** [comment]
@emileaben do you have any preferences between these two graphs?

**Comment by Rithvik-padma** [comment]
> thanks, I think I prefer when there a line. But I really wished that the line gets cut when there is missing data, but that's maybe not possible with plotly. Or maybe we should create different traces with the same color? (one before the cut and one after) but then I'm afraid that the legend will have duplicated entries

Yes, ig there would be duplicate entries in the legend. I did not actually think of this approach, if possible I will work more on it but I think we can make a temporary fix by choosing any of these two graph types.

**Comment by romain-fontugne** [comment]
OK, then let's go with the markers only

**Comment by Rithvik-padma** [comment]
> OK, then let's go with the markers only

Great I will make a PR soon!

**Comment by anugcodes** [comment]
@romain-fontugne   @Rithvik-padma  ,  the line charts can be cut  in PlotlyJs. I went through the docs and found this 
![image](https://user-images.githubusercontent.com/110781959/233849795-048e805b-a4c7-4bbe-85fa-d1b0e4bf62be.png)
this property allows to have disconnected graph. 
this is the final result , 

![image](https://user-images.githubusercontent.com/110781959/233849950-71d75210-f2f9-41dc-b075-2dfa4fe13817.png)

**Comment by anugcodes** [comment]
also this is the result without using markers 
![image](https://user-images.githubusercontent.com/110781959/233850266-e525c59f-62ad-49f0-9a74-5a32661c9f68.png)

while using lines only the points in the middle are removed

**Comment by Rithvik-padma** [comment]
> @romain-fontugne @Rithvik-padma , the line charts can be cut in PlotlyJs. I went through the docs and found this ![image](https://user-images.githubusercontent.com/110781959/233849795-048e805b-a4c7-4bbe-85fa-d1b0e4bf62be.png) this property allows to have disconnected graph. this is the final result ,
> 
> ![image](https://user-images.githubusercontent.com/110781959/233849950-71d75210-f2f9-41dc-b075-2dfa4fe13817.png)

@anugcodes I guess there is no use in using the connectgaps property as by default it is set to false so that is the reason I did not use it, but anyway thanks for the reply as I have checked again by adding connectgaps but it did not work but I found that the logic code used for setting null values in the data did not work correctly, I have tested it and  So I have changed the logic for it and now it works fine.
I don't know how did you get the correct graphs for it as the logic is not working as it should.
Anyways I am making a PR to make these changes.
Thanks for pointing this out!

**Comment by anugcodes** [comment]
> > @romain-fontugne @Rithvik-padma , the line charts can be cut in PlotlyJs. I went through the docs and found this ![image](https://user-images.githubusercontent.com/110781959/233849795-048e805b-a4c7-4bbe-85fa-d1b0e4bf62be.png) this property allows to have disconnected graph. this is the final result ,
> > ![image](https://user-images.githubusercontent.com/110781959/233849950-71d75210-f2f9-41dc-b075-2dfa4fe13817.png)
> 
> @anugcodes I guess there is no use in using the connectgaps property as by default it is set to false so that is the reason I did not use it, but anyway thanks for the reply as I have checked again by adding connectgaps but it did not work but I found that the logic code used for setting null values in the data did not work correctly, I have tested it and So I have changed the logic for it and now it works fine. I don't know how did you get the correct graphs for it as the logic is not working as it should. Anyways I am making a PR to make these changes. Thanks for pointing this out!

Yes you are right, i too had to correct the way the two dates were compared.
![image](https://user-images.githubusercontent.com/110781959/233909504-8ea89b74-cf0c-4561-8abe-f72a991048c2.png)
so the actual problem was here.

**Comment by romain-fontugne** [comment]
thanks guys, great work!

**Comment by romain-fontugne** [comment]
fixed by  #448
